### ISSUE TITLE
Failed to build Xcode project

### ISSUE THREAD

**Issue by kitasuke** [bitrise-samples/macos-sample-app#1]
## Issue

I failed to build this project and got an error below.

## Steps to reproduce

1. Clone this repository
2. Open Xcode
3. Build macOS-sample-app

## Environment 

Xcode: Version 10.0 (10A255)

## Screenshot

<img width="491" alt="Screen Shot 2019-03-09 at 21 29 21" src="https://user-images.githubusercontent.com/1732312/54071662-1925d600-42b3-11e9-8f16-e034f7b50b65.png">

**Comment by fehersanyi-bitrise** [comment]
Hello there!

Well you would need to have the proper code signing identity to build this app, and this is of the bitrise developer team. That is all. 🙃

**Comment by kitasuke** [comment]
Are you aware that this sample project is used for test of bitrise steps?
For example, if I run `bitrise test run` in bitrise-steplib/steps-xcode-test-mac repository on my local, test is failed because of error above. Is this expected behavior? @fehersanyi-bitrise 
https://github.com/bitrise-steplib/steps-xcode-test-mac/blob/master/bitrise.yml#L8

FYI
https://github.com/bitrise-steplib/steps-xcode-test-mac/pull/11#issuecomment-471282200

**Comment by fehersanyi-bitrise** [comment]
Could you send me the log to the test run please so I can check it out for some more detail?
also, I created a card for the tooling team to review your PR

**Comment by kitasuke** [comment]
Attached the error log
[error.log](https://github.com/bitrise-samples/macos-sample-app/files/2956428/error.log)

**Comment by BirmacherAkos** [comment]
Hi @kitasuke !

I've removed the `developer team` from the targets (App, Unit, UI) https://github.com/bitrise-samples/macos-sample-app/commit/3c4563e6773a04cd6099c0501c68b5a1ca353133. 
With that, you should be able to build/run the project on your mac as well.

**Comment by kitasuke** [comment]
Awesome, thank you!
